apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-discovery
spec:
  template:
    metadata:
      labels:
        run: kubernetes-discovery
    spec:
      containers:
      - name: kubernetes-discovery
        image: remotejob/kubernetes-discovery:0.0 
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        ports:
        - containerPort: 8000
