apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cv-app
spec:
  template:
    metadata:
      labels:
        run: cv-app
    spec:
      containers:
      - name: cv-app
        image:  remotejob/discovery
        env:
        - name: SECRET_USERNAME
          value: admin
        - name: SECRET_PASSWORD
          value: admin1Rel
        ports:
        - containerPort: 8000
